model {
  file: "model.sdf"
}
name: "ir_towel"
description: "towel"
version: 1
authors {
  name: "Google"
  email: "scanned-objects@google.com"
}
legal {
  copyright: "Copyright 2020 Google LLC."
  license: "Creative Commons Attribution 4.0 International"
}
annotations {
  key: "brand"
  value: "Provence"
}
annotations {
  key: "gtin"
  value: "00761450086333"
}
annotations {
  key: "sku"
  value: "00761450086333"
}
compatibilities {
  name: "Gazebo"
  version {
    major: 11
  }
}
categories {
}
